options:
  public:
    description: require login or make a public accessible irc bouncer
    default: false
    type: boolean
  port:
    default: 80
    description: |
      Port to run shout on
    type: int
  extra_packages:
    description: >
        Space separated list of extra deb packages to install.
    type: string
    default: ""
  package_status:
    default: "install"
    type: string
    description: >
        The status of service-affecting packages will be set to this
        value in the dpkg database. Valid values are "install" and "hold".
  install_sources:
    description: >
        List of extra apt sources, per charm-helpers standard
        format (a yaml list of strings encoded as a string). Each source
        may be either a line that can be added directly to
        sources.list(5), or in the form ppa:<user>/<ppa-name> for adding
        Personal Package Archives, or a distribution component to enable.
    type: string
    default: |
      - https://deb.nodesource.com/node_6.x main
  install_keys:
    description: >
        List of signing keys for install_sources package sources, per
        charmhelpers standard format (a yaml list of strings encoded as
        a string). The keys should be the full ASCII armoured GPG public
        keys. While GPG key ids are also supported and looked up on a
        keyserver, operators should be aware that this mechanism is
        insecure. null can be used if a standard package signing key is
        used that will already be installed on the machine, and for PPA
        sources where the package signing key is securely retrieved from
        Launchpad.
    type: string
    default: |
      - '68576280'
