#!/usr/local/sbin/charm-env python3
from subprocess import PIPE, Popen
from charmhelpers.core.hookenv import action_get


if __name__ == "__main__":
    username = action_get('username')
    password = action_get('password')

    p = Popen(
        [
            "/snap/bin/theloungeirc.thelounge-cli",
            "reset",
            username
        ],
        stdin=PIPE,
        stdout=PIPE,
        stderr=PIPE,
        encoding='utf8'
    )
    p.communicate("{}\n".format(password))
