#!/usr/bin/python3

import sys
sys.path.append('lib')
sys.path.append('hooks')

from charms.layer.lounge import Lounge
from charms.layer.nodejs import node_dist_dir

from charmhelpers.core.hookenv import (
    action_get,
    action_fail,
)

lounge = Lounge(node_dist_dir())

try:
    lounge.remove(action_get('name'))
except Exception as e:
    action_fail("%s" % e)
